# Generated by Django 5.2.1 on 2025-05-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_author', models.CharField(max_length=100)),
                ('last_description', models.TextField(max_length=200)),
                ('last_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('list_messages', models.ManyToManyField(blank=True, related_name='list_messages', to='message.message')),
            ],
        ),
    ]
