# Generated by Django 5.2.1 on 2025-05-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('assignments', models.ManyToManyField(blank=True, related_name='courses', to='assignments.assignment')),
                ('lectures', models.ManyToManyField(blank=True, related_name='courses', to='lectures.lecture')),
            ],
            options={
                'db_table': 'course',
                'ordering': ['name'],
            },
        ),
    ]
