# Generated by Django 5.2.1 on 2025-05-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('lectures', '0001_initial'),
        ('profiles', '0001_initial'),
        ('tests', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('assignments', models.ManyToManyField(blank=True, related_name='assignments', to='assignments.assignment')),
                ('lectures', models.ManyToManyField(blank=True, related_name='lectures', to='lectures.lecture')),
                ('profiles', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.profile')),
                ('tests', models.ManyToManyField(blank=True, related_name='tests', to='tests.tests')),
                ('threads', models.ManyToManyField(blank=True, related_name='threads', to='threads.thread')),
            ],
            options={
                'db_table': 'course',
                'ordering': ['name'],
            },
        ),
    ]
