# Generated by Django 5.2.1 on 2025-05-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('profiles', '0001_initial'),
        ('tests', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='courses', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='course',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='courses', to='tests.tests'),
        ),
        migrations.AddField(
            model_name='course',
            name='threads',
            field=models.ManyToManyField(blank=True, related_name='courses', to='threads.thread'),
        ),
    ]
