# Generated by Django 5.2.1 on 2025-06-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_description_course_image_course_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
    ]
