# Generated by Django 5.2.1 on 2025-05-21 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_course', to='course.course')),
                ('list_courses', models.ManyToManyField(to='course.course')),
            ],
        ),
    ]
