# Generated by Django 5.2.1 on 2025-05-26 20:31

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('submitter', models.CharField(blank=True, max_length=100, null=True)),
                ('date_due', models.DateTimeField(blank=True, null=True)),
                ('max_points', models.IntegerField(blank=True, null=True)),
                ('student_points', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('assignment_file', models.FileField(blank=True, null=True, storage=assignments.models.select_storage, upload_to='assignments/')),
                ('student_file', models.FileField(blank=True, null=True, storage=assignments.models.select_storage, upload_to='assignments/')),
            ],
            options={
                'db_table': 'assignment',
                'ordering': ['date_due'],
            },
        ),
    ]
