# Generated by Django 5.2.1 on 2025-06-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='graded_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
