# Generated by Django 5.2.1 on 2025-08-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignmentsubmission_graded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
