# Generated by Django 5.2.1 on 2025-08-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
