# Generated by Django 5.2.1 on 2025-05-26 20:31

import lectures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(null=True, storage=lectures.models.select_storage, upload_to='lectures/')),
            ],
            options={
                'db_table': 'lecture',
                'ordering': ['name'],
            },
        ),
    ]
