# Generated by Django 5.2.1 on 2025-05-26 20:31

import tests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('date_due', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('submitter', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=tests.models.select_storage, upload_to='tests/')),
                ('student_file', models.FileField(blank=True, null=True, storage=tests.models.select_storage, upload_to='tests/')),
                ('max_points', models.IntegerField(blank=True, null=True)),
                ('student_points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tests',
                'ordering': ['date_due'],
            },
        ),
    ]
